### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by SwiftCODA** [Lierrmm/Node-CallOfDuty#113]
How are you getting around the captcha for the login request?

**Comment by Lierrmm** [comment]
We don't accept credentials for login. 

You need to use the 'ACT_SSO_TOKEN' cookie and include it within all your requests.

See Linked Code: https://github.com/Lierrmm/Node-CallOfDuty/blob/4ac8f0b63b90b5afa917e856186760db5e823654/src/index.ts#L119

**Comment by SwiftCODA** [comment]
> We don't accept credentials for login.
> 
> You need to use the 'ACT_SSO_TOKEN' cookie and include it within all your requests.
> 
> See Linked Code:
> 
> https://github.com/Lierrmm/Node-CallOfDuty/blob/4ac8f0b63b90b5afa917e856186760db5e823654/src/index.ts#L119

So for your initial authentication to get that sso token, you just do it in a browser and then copy it over?

Does it expire or have limited uses?

Are you familiar with the legal side of things and how Activision feels about third-parties utilizing their data? I've read that they are only partner with Tracker Network and will come after any other large-ish organization using their API...

**Comment by Lierrmm** [comment]
> > We don't accept credentials for login.
> > You need to use the 'ACT_SSO_TOKEN' cookie and include it within all your requests.
> > See Linked Code:
> > https://github.com/Lierrmm/Node-CallOfDuty/blob/4ac8f0b63b90b5afa917e856186760db5e823654/src/index.ts#L119
> 
> So for your initial authentication to get that sso token, you just do it in a browser and then copy it over?
> 
> Does it expire or have limited uses?
> 
> Are you familiar with the legal side of things and how Activision feels about third-parties utilizing their data? I've read that they are only partner with Tracker Network and will come after any other large-ish organization using their API...

1. Yes - login to the my.callofduty.com website via the browser and copy the cookie. ( I have a 'legacy' branch on this repo which contains a method of bypassing the captcha using puppeteer and a service called '2captcha', however, its a paid product which is why this method was removed - along with it taking up to 60 seconds to complete the captcha )
2. Never Expires (only a session based cookie in browser)
3. Can't comment on legal side - its a publicly exposed API and this wrapper has been around since 2017 with no issues from Activision.
