### ISSUE TITLE
Error: 401 - Unauthorized. Incorrect username or password

### ISSUE THREAD

**Issue by dorumrr** [Lierrmm/Node-CallOfDuty#68]
Hi,
It seems that the login suddenly returns `Error: 401 - Unauthorized. Incorrect username or password` although the credentials are working just fine on the website and used to be working just fine until this morning. I get the same error on  both v1.3.4 (my current), and v1.3.5 (your latest).
Any ideas?

**Comment by fakhir-shad** [comment]
I am also receiving the same error. It started happening a day ago for me. I have even tried with a new account.

**Comment by spanciu** [comment]
@dorumrr @fakhir-shad 
Something changed on the Login API on Call of Duty side. As far as I know @Lierrmm  is working on it already :D

**Comment by Lierrmm** [comment]
See https://www.npmjs.com/package/call-of-duty-api/v/2.0.0-dev for a temporary fix for now.

Dev build which fixes the recent changes. `npm i call-of-duty-api@2.0.0-dev`

Notes: 
- When using the dev version, call login once, otherwise you may run into issues.
- it is not the final version so I'm not pushing it to the main repo.

Downsides:
- Will not work in the browser as it uses puppeteer 
- possibly slower than usual

I will be working on a proper fix over the next couple of days
